# 에러 처리

## 에러 처리의 필요성

- 에러(`error`)가 발생하지 않는 코드를 작성하는 것은 불가능.
- 에러는 언제나 발생할 수 있으며, 발생한 에러에 대해 대처하지 않고 방치하면 프로그램은 강제 종료.
- `try ... catch` 문을 사용해 발생한 에러에 적절하게 대응하면 프로그램이 강제 종료되지 않고 계속해서 코드를 실행시킬 수 있음.
- 직접적으로 에러를 발생하지 않는 예외(`exception`)적인 상황이 발생할 수도 있음.
  - 예외 상황에 적절하게 대응하지 않으면 에러로 이어질 가능성 多.

---

## `try ... catch ... finally` 문

- 에러 처리를 구현하는 두 가지 방법

  1. 예외적인 상황이 발생하면 반환하는 값(`null` 또는 `-1`)을 `if` 문이나 단축 평가 또는 옵셔널 체이닝 연산자를 통해 확인해서 처리.
  2. 에러 처리 코드를 미리 등록해 두고 에러가 발생하면 에러 처리 코드로 점프하도록 유도.

- `try ... catch ... finally` 문은 두 번째 방법으로, 일반적으로 이 방법을 에러 처리(`error handling`)라고 함.
- `finally` 문은 불필요하다면 생략 가능.

```js
console.log("[Start]");
try {
  // 실행할 코드(에러가 발생할 가능성이 있는 코드)
  foo();
} catch (e) {
  // try 코드 블록에서 에러가 발생하면 이 코드 블록의 코드가 실행
  // e에는 try 코드 블록에서 발생한 Error 객체가 전달
  console.error(e); // ReferenceError: foo is not defined
} finally {
  // 에러 발생과 상관없이 반드시 한 번 실행
  console.log("finally");
}
console.log("[End]");
```

- 에러를 처리하면 프로그램이 강제 종료되지 않음.

---

## `Error` 객체

- `Error` 생성자 함수는 에러 객체를 생성.
- `Error` 생성자 함수에는 에러를 상세히 설명하는 에러 메세지를 인수로 전달 가능.

```js
const error = new Error("invalid");
```

- `Error` 생성자 함수가 생성한 에러 객체는 `message` 프로퍼티와 `stack` 프로퍼티를 가짐.
- `message` 프로퍼티의 값은 `Error` 생성자 함수에 인수로 전달한 에러 메세지.
- `stack` 프로퍼티의 값은 에러를 발생시킨 콜스택의 호출 정보를 나타내는 문자열.(디버깅 목적)
- `JavaScript` 에서 제공하는 `Error` 객체는 7가지로, 모두 `Error.prototype`을 상속 받음.

|   생성자 함수    |                                      인스턴스                                      |
| :--------------: | :--------------------------------------------------------------------------------: |
|     `Error`      |                                  일반적 에러 객체                                  |
|  `SyntaxError`   |             `JavaScript` 문법에 맞지 않는 문을 해석할 때 발생하는 객체             |
| `ReferenceError` |               참조할 수 없는 식별자를 참조했을 때 발생하는 에러 객체               |
|   `TypeError`    |       피연산자 또는 인수의 데이터 타입이 유효하지 않을 때 발생하는 에러 객체       |
|   `RangeError`   |                숫자값의 허용 범위를 벗어났을 때 발생하는 에러 객체                 |
|    `URIError`    | `encodeURI` 또는 `decodeURI` 함수에 부적절한 인수를 전달했을 때 발생하는 에러 객체 |
|   `EvalError`    |                           `eval` 함수에서 발생하는 객체                            |

```js
1 @ 1;                      // SyntaxError: Invalid or unexcepted token
foo();                      // ReferenceError: foo is not defined
null.foo;                   // TypeError: Cannot read property 'foo' of null
new Array(-1);              // RangeError: Invalid array length
decodeURIComponent("%");    // URIError: URI malformed
```

---

## `throw` 문

- `Error` 생성자 함수로 에러 객체를 생성한다고 에러가 발생하는 것은 아님.
- 에러 객체 생성과 에러 발생은 의미가 다름.
- 에러를 발생시키려면 `try` 코드 블록에서 `throw` 문으로 에러 객체를 던져야 함.

```js
throw 표현식;
```

- `throw` 문의 표현식은 어떤 값이라도 상관없지만 일반적으로 에러 객체를 지정.
- 에러를 던지면 `catch` 문의 에러 변수가 생성되고 던져진 에러 객체가 할당.

```js
const repeat = (n, f) => {
  if (typeof f !== "function") throw new TypeError("f must be a function");

  for (var i = 0; i < n; i++) {
    f(i);
  }
};

try {
  repeat(2, 1);
} catch (e) {
  console.error(e);
}
```

---

## 에러의 전파

- 에러는 호출자(`caller`) 방향으로 전파. 즉, 콜 스택의 아래 방향으로 전파

```js
const foo = () => {
  throw new Error("foo에서 발생한 에러");
};

const bar = () => {
  foo();
};

const baz = () => {
  bar();
};

try {
  baz();
} catch (e) {
  // foo 함수의 에러가 전역에서 캐치
  console.error(e);
}
```

- `throw`된 에러를 캐치하지 않으면 호출자 방향으로 전파(`foo` -> `bar` -> `baz` -> 전역).
- `throw`된 에러를 어디에서도 캐치하지 않으면 프로그램은 강제 종료.
- 비동기 함수인 `setTimeout`이나 프로미스 후속 처리 메서드의 콜백 함수는 콜 스택이 비면 푸시되어 콜 스택의 가장 하부에 존재하므로 에러를 전파할 호출자가 존재하지 않음에 주의.
