# 47장. 에러처리

## 47.1 에러처리의 필요성

에러가 발생하지 않는 코드는 작성 불가능하다.

try...catch문을 사용해 발생한 에러에 적절하게 대응하면 프로그램이 강제 종료되지 않고 계속해서 코드를 실행시킬 수 있다.

```js
console.log('[Start]');
try {
  foo();
} catch (error) {
  console.error('[Error]', error);
}
```

에러가 발생하지 않는 코드를 작성할 수는 없다. 따라서 우리가 작성한 코드에서는 언제나 에러나 예외적인 상황이 발생할 수 있다는 것을 전제하고 **이에 대응하는 코드를 작성하는 것이 중요하다.**

## 47.2 try...catch...finally문

기본적으로 에러 처리는 2가지 방법이 존재한다.

1. 예외적인 상황이 발생하면 if문이나 옵셔널체이닝 연산자를 통한 확인

2. 에러처리 코드를 미리 등록해두고 에러가 발생하면 에러 처리코드로 점프시키기

try...catch...finally문이 `2번째 방법`이다. 이 방법을 **에러 처리** 라고 한다.

```js
try {
  // 실행할 코드(에러가 발생할 가능성이 있는 코드)
} catch (err) {
  // try 코드 블록에서 에러가 발생하면 이 코드 블록의 코드가 실행된다.
  // err에는 try 코드 블록에서 발생한 Error 객체가 전달된다.
} finnaly {
  // 에러 발생과 상관없이 반드시 한 번 실행된다.
}
```

try가 실행되고 try 내에서 에러가 발생하면 catch의 err 변수에 전달되고 catch 블록이 실행된다.

finally 코드 블록은 에러 발생과 상관없이 반드시 한 번 실행된다.

## 47.3 Error 객체

Error 생성자 함수는 에러 객체를 생성한다. Error 생성자 함수에는 에러를 상세히 설명하는 에러 메세지를 인수로 전달할 수 있다.

```js
const error = new Error('invalid');
```

Error 생성자 함수가 생성한 에러 객체는 message 프로퍼티와 stack 프로퍼티를 갖는다. message는 인수로 전달한 에러메시지이고 stack은 에러를 발생시킨 콜스택의 호출정보를 담는다. (디버깅 할 때 사용)

## 47.4 throw문

Error 생성자 함수로 에러 객체를 생성한다고 에러가 발생하는 것은 아니다. **즉, 에러 객체 생성과 에러 발생은 의미가 다르다.**

```js
try {
  // 에러 객체를 던지면 catch 코드 블록이 실행되기 시작한다.
  throw new Error('something wrong');
} catch (error) {
  console.log(error);
}
```

에러를 발생시키려면 try 코드 블록에서 throw문으로 에러 객체를 던져야 한다.

## 47.5 에러의 전파

에러는 호출자 방향으로 전파된다.

```js
const foo = () => {
  throw Error('foo에서 발생한 에러'); // ④
};

const bar = () => {
  foo(); // ③
};

const baz = () => {
  bar(); // ②
};

try {
  baz(); // ①
} catch (err) {
  console.error(err);
}
```

- 1에서 baz 함수를 호출하면 2에서 bar함수가 호출되고 3에서 foo함수가 호출되고 foo함수는 4에서 에러를 throw한다. 이때 foo함수가 throw한 에러는 다음과 같이 호출자에게 전파되어 전역에서 캐치된다.

- throw된 에러를 캐치하지 않으면 호출자 방향으로 전파된다. 이때 throw된 에러를 캐치하여 적절히 대응하면 프로그램을 강제 종료 시키지 않고 코드의 실행 흐름을 복구할 수 있다.

- throw된 에러를 어디에서도 캐치하지 않으면 프로그램은 강제 종료된다.
