# 47장 에러 처리

우리가 작성한 코드에서는 언제나 예외적인 상황이 발생할 수 있다는 것을 전제하고 이에 대응하는 코드를 작성하는 것이 중요하다.

기본적으로 에러 처리를 구현하는 방법은 크게 두 가지가 있다.

- if문 / 단축 평가 / 옵셔널 체이닝 연산자: querySelector나 Array#find 메서드처럼 예외적인 상황이 발생하면 반환하는 값(null, -1 등)을 통해 처리하는 방법이다.
- try ... catch ... finally 문: 실행할 코드, 에러를 처리할 코드, 에러 발생과 상관없이 실행할 코드를 통해 처리하는 방법이다. 이렇게 에러를 처리하면 프로그램이 강제 종료되지 않는다.

<br>

## Error 객체와 throw 문

에러 객체는 Error 생성자 함수로 생성할 수 있으며 에러 메시지를 인수로 전달할 수 있다. 또한 message 프로퍼티와 stack 프로퍼티를 갖는다.

- message 프로퍼티: 생성자 함수로 전달한 에러 메시지다.
- stack 프로퍼티: 에러를 발생시킨 콜 스택의 호출 정보를 나타내는 문자열이며 디버깅 목적으로 사용한다.

자바스크립트에는 7가지 에러 객체를 생성할 수 있는 Error 생성자 함수를 제공한다.

- Error
- SyntaxError: 문법에 맞지 않는 문을 해석할 때 발생한다.
- ReferenceError: 참조할 수 없는 식별자를 참조했을 때 발생한다.
- TypeError
- RangeError: 숫자값의 허용 범위를 벗어났을 때 발생한다.
- URIError: encodeURI 또는 decodeURI 함수에 부적절한 인수를 전달했을 때 발생한다.
- EvalError: eval 함수에서 발생하는 에러 객체다.

에러객체 생성과 에러 발생은 의미가 다르다. 에러를 발생시키려면 try 코드 블록에서 throw 문으로 객체를 던져야 한다.

```js
const repeat = (n, f) => {
  if (typeof f !== 'function') {
    throw new TypeError('f must be a function');
  }

  for (var i = 0; i < n; i++) {
    f(i);
  }
};

try {
  repeat(2, 1); // 두 번째 인수는 함수여야 한다.
} catch (error) {
  console.error(err); // TypeError: f must be a function
}
```

<br>

## 에러의 전파

에러는 콜 스택의 아래 방향, 호출자(caller) 방향으로 전파된다.

```js
const foo = () => {
  throw Error('Error in foo');
};

const bar = () => {
  foo();
};

const baz = () => {
  bar();
};

try {
  baz();
} catch (error) {
  console.error(error);
}
```

![](assets/47-1)

- foo 함수가 throw한 에러는 그림과 같이 호출자에게 전파되어 전역에서 캐치된다.
- throw된 에러를 캐치하지 않으면 프로그램은 강제 종료된다.

비동기 함수인 setTimeout이나 프로미스 후속 처리 메서드의 콜백 함수는 이벤트 루프에 의해 콜 스택의 가장 하부에 존재하게 되므로 에러를 전파할 호출자가 존재하지 않는다.

---

## Deep Dive

### Error Handling in setTimeout

```js
// #1. try ... catch 문을 포함하는 콜백을 정의하기
setTimeout(() => {
  try {
    throw new Error(`Error ...`);
  } catch (error) {
    console.error(error);
  }
}, 500);
```

```js
// #2. 고차 함수를 사용해 에러 처리하기
function errorHandle(process) {
  return function () {
    try {
      return process.apply(this, arguments);
    } catch (e) {
      console.error(e);
    }
  };
}

setTimeout(
  errorHandle(function () {
    throw new Error(`Error ...`);
  }),
  1000
);
```
